### ISSUE TITLE
Can't git clone

### ISSUE THREAD

**Issue by fckveza** [app-generator/flask-soft-ui-dashboard-pro#2]
how to git this repo? i jave buy pro version

**Comment by app-generator** [comment]
Hello @fckveza,

Access to the private repository is unlocked by the `company` license.

Please contact support using email or Discord for further assistance:

- support@appseed.us
- https://discord.gg/fZC6hup

**Comment by fckveza** [comment]
so how do i run the flask soft ui pro that i bought?
